### ISSUE TITLE
vanilla example

### ISSUE THREAD

**Issue by meiyasan** [kreudev/editorjs-mention-tool#1]
Hello, great work @kreudev  ! This was really a missing piece in EditorJS.
Is it possible to get a working example code without react ? using the default configuration there is a small issue
```

        var editor = new EditorJs({tools: {
            mention: {
                class: MentionTool,
                config: {
                    holder: 'editorHolder', // This is the editor Holder ( see below )
                    accessKey: "@", // Access key ( $ or @ )
                    allUsers: [ // The array with the data you want to show when the users type $
                        {
                            "id": "1234",
                            "name": "Variable 1",
                            "slug": "variable1"
                        },
                        {
                            "id": "12345",
                            "name": "Thing of v1",
                            "slug": "variable1.something"
                        },
                    ],
                    baseUrl: '', 
                    searchAPIUrl: ''
                }
            },
[..]
});

```

```
editor.js:2 Paste handling for «mention» Tool hasn't been set up because of the error TypeError: Cannot read properties of undefined (reading 'forEach')
    at MentionTool.cacheAllUsersAsUserListItems (index.js:273:1)
    at new MentionTool (index.js:54:1)
    at n.value (editor.js:2:429389)
    at e.processTool (editor.js:2:227620)
    at Array.forEach (<anonymous>)
    at w.value (editor.js:2:231492)
    at w.<anonymous> (editor.js:2:228716)
    at p (editor.js:2:356625)
    at Generator.<anonymous> (editor.js:2:357976)
    at Generator.next (editor.js:2:356996)
```

**Comment by meiyasan** [comment]
Any help about AJAX call request would be great too ! I already have a backend controller following this standard:
https://www.npmjs.com/package/@mrpritchett/editorjs-mentions

**Comment by Hesesses** [comment]
Any updates on this?

**Comment by meiyasan** [comment]
eventually developed my own editors-mention tool. I don't think author will do anything about it.
I close this issue, please reopen if necessary.

**Comment by Hesesses** [comment]
@meiyasan If you dont mind sharing your solution, i would be super thankful 🙏

**Comment by meiyasan** [comment]
I can try to prepare a comprehensive example over the week-end, please wait a bit 😊

**Comment by Bjeaurn** [comment]
Very curious to your solution, if you still would like to post it!

**Comment by gs03-dev** [comment]
Here you guys go

```import { API } from "@editorjs/editorjs";
import { createRoot, Root } from "react-dom/client";
import React from "react";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";

interface MentionConfig {
  endpoint?: string;
  users?: Array<{ id: string; name: string; avatar?: string }>;
  queryParam?: string;
  debounce?: number;
  pageSize?: number;
}

interface PaginatedResponse {
  users: Array<{ id: string; name: string; avatar?: string }>;
  hasMore: boolean;
  total?: number;
}

interface MentionDropdownProps {
  users: Array<{ id: string; name: string; avatar?: string }>;
  hasMore: boolean;
  isLoading: boolean;
  onSelect: (user: { id: string; name: string }) => void;
  onLoadMore: () => void;
  open: boolean;
  position: { top: number; left: number };
}

const MentionDropdown: React.FC<MentionDropdownProps> = ({
  users,
  hasMore,
  isLoading,
  onSelect,
  onLoadMore,
  open,
  position,
}) => {
  const handleScroll = (e: React.UIEvent<HTMLDivElement>) => {
    if (isLoading || !hasMore) return;

    const target = e.currentTarget;
    const { scrollTop, scrollHeight, clientHeight } = target;
    if (scrollTop + clientHeight >= scrollHeight - 20) {
      onLoadMore();
    }
  };

  if (!open) return null;

  return (
    <div
      className="fixed w-[280px] bg-white border border-gray-200 rounded-lg shadow-lg z-[9999] p-2"
      style={{
        top: `${position.top}px`,
        left: `${position.left}px`,
        pointerEvents: "auto",
      }}
      onMouseDown={(e) => {
        e.preventDefault();
        e.stopPropagation();
      }}
      onClick={(e) => {
        e.preventDefault();
        e.stopPropagation();
      }}
    >
      <div className="max-h-[280px] overflow-y-auto" onScroll={handleScroll}>
        <div className="space-y-1">
          {users.map((user) => (
            <div
              key={user.id}
              className="flex items-center gap-3 p-2 rounded-md hover:bg-accent cursor-pointer transition-colors"
              onMouseDown={(e) => {
                e.preventDefault();
                e.stopPropagation();
                onSelect(user);
              }}
            >
              <Avatar className="h-8 w-8">
                <AvatarImage src={user.avatar} alt={user.name} />
                <AvatarFallback>
                  {user.name.charAt(0).toUpperCase()}
                </AvatarFallback>
              </Avatar>
              <span className="text-sm font-medium">{user.name}</span>
            </div>
          ))}
          {hasMore && (
            <div className="text-center py-2 text-xs text-muted-foreground italic">
              {isLoading ? "Loading..." : "Scroll for more"}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default class MentionTool {
  private api: API;
  private config: MentionConfig;
  private popoverContainer: HTMLDivElement | null = null;
  private reactRoot: Root | null = null;
  private allUsers: Array<{ id: string; name: string; avatar?: string }> = [];
  private filteredUsers: Array<{ id: string; name: string; avatar?: string }> =
    [];
  private mentionStart = -1;
  private searchQuery = "";
  private debounceTimer: NodeJS.Timeout | null = null;
  private currentBlock: HTMLElement | null = null;
  private currentPage = 1;
  private hasMore = false;
  private isLoading = false;
  private isOpen = false;
  private dropdownPosition = { top: 0, left: 0 };
  private selectedMentionIds: Set<string> = new Set();

  static get isInline() {
    return true;
  }

  static get sanitize() {
    return {
      span: {
        class: "mention",
        "data-mention-id": true,
        "data-mention-name": true,
      },
    };
  }

  constructor({ api, config }: { api: API; config?: MentionConfig }) {
    this.api = api;
    this.config = config || {};
    this.allUsers = this.config.users || [];

    setTimeout(() => this.init(), 100);
  }

  private init() {
    const editorElement = document.querySelector(".codex-editor") as any;
    if (!editorElement) return;

    editorElement.addEventListener("input", this.handleInput.bind(this), true);
    editorElement.addEventListener(
      "keydown",
      this.handleKeydown.bind(this),
      true
    );

    document.addEventListener("mousedown", (e) => {
      if (
        this.popoverContainer &&
        !this.popoverContainer.contains(e.target as Node)
      ) {
        this.closeDropdown();
      }
    });

    // Track mentions in the editor
    this.trackMentions();
  }

  private trackMentions() {
    const editorElement = document.querySelector(".codex-editor");
    if (!editorElement) return;

    // Initial scan
    this.updateSelectedMentions();

    // Watch for changes using MutationObserver
    const observer = new MutationObserver(() => {
      this.updateSelectedMentions();
    });

    observer.observe(editorElement, {
      childList: true,
      subtree: true,
      attributes: true,
      attributeFilter: ["data-mention-id"],
    });
  }

  private updateSelectedMentions() {
    const editorElement = document.querySelector(".codex-editor");
    if (!editorElement) return;

    const mentionElements = editorElement.querySelectorAll(
      ".mention[data-mention-id]"
    );
    this.selectedMentionIds.clear();

    mentionElements.forEach((el) => {
      const mentionId = el.getAttribute("data-mention-id");
      if (mentionId) {
        this.selectedMentionIds.add(mentionId);
      }
    });
  }

  render() {
    const button = document.createElement("button");
    button.type = "button";
    button.innerHTML = `
      <svg width="17" height="17" viewBox="0 0 17 17" xmlns="http://www.w3.org/2000/svg">
        <path d="M8.5 1C4.91 1 2 3.91 2 7.5S4.91 14 8.5 14 15 11.09 15 7.5 12.09 1 8.5 1zm0 11.5c-2.76 0-5-2.24-5-5s2.24-5 5-5 5 2.24 5 5-2.24 5-5 5z"/>
        <text x="8.5" y="11" text-anchor="middle" font-size="8" font-weight="bold" fill="currentColor">@</text>
      </svg>
    `;
    return button;
  }

  surround() {
    const selection = window.getSelection();
    if (!selection) return;

    document.execCommand("insertText", false, "@");
  }

  checkState() {
    return false;
  }

  private handleInput(e: Event) {
    const target = e.target as HTMLElement;

    if (!target.isContentEditable) return;
    if (target.closest(".ce-toolbar")) return;

    this.currentBlock = target;
    const text = target.innerText || "";
    const cursorPos = this.getCursorPosition(target);

    const lastAtPos = text.lastIndexOf("@", cursorPos);

    if (lastAtPos !== -1 && cursorPos - lastAtPos <= 50) {
      const charBeforeAt = lastAtPos > 0 ? text[lastAtPos - 1] : " ";

      if (lastAtPos === 0 || /\s/.test(charBeforeAt)) {
        this.mentionStart = lastAtPos;
        this.searchQuery = text.substring(lastAtPos + 1, cursorPos);
        this.currentPage = 1;
        this.updateDropdownPosition();
        this.debouncedSearch();
        return;
      }
    }

    this.closeDropdown();
  }

  private handleKeydown(e: KeyboardEvent) {
    if (!this.isOpen) return;

    const target = e.target as HTMLElement;
    if (!target.isContentEditable) return;

    if (e.key === "Escape") {
      e.preventDefault();
      e.stopPropagation();
      this.closeDropdown();
    }
  }

  private updateDropdownPosition() {
    const selection = window.getSelection();
    if (!selection || selection.rangeCount === 0) return;

    const range = selection.getRangeAt(0);
    const rect = range.getBoundingClientRect();

    // Position dropdown below the cursor with some offset
    this.dropdownPosition = {
      top: rect.bottom + window.scrollY + 5,
      left: rect.left + window.scrollX,
    };
  }

  private debouncedSearch() {
    if (this.debounceTimer) {
      clearTimeout(this.debounceTimer);
    }

    this.debounceTimer = setTimeout(() => {
      this.searchUsers(this.searchQuery);
    }, this.config.debounce || 150);
  }

  private async searchUsers(query: string) {
    this.isLoading = true;
    // Update the list of selected mentions before filtering
    this.updateSelectedMentions();

    let filteredUsers: Array<{ id: string; name: string; avatar?: string }> =
      [];

    if (this.config.endpoint) {
      try {
        const pageSize = this.config.pageSize || 20;
        const url = `${this.config.endpoint}?${
          this.config.queryParam || "q"
        }=${encodeURIComponent(query)}&page=${
          this.currentPage
        }&limit=${pageSize}`;
        const response = await fetch(url);
        const data: PaginatedResponse = await response.json();

        filteredUsers = data.users || (data as any);
        this.hasMore = data.hasMore || false;

        if (this.currentPage === 1) {
          this.filteredUsers = filteredUsers;
        } else {
          this.filteredUsers = [...this.filteredUsers, ...filteredUsers];
        }
      } catch (error) {
        console.error("Error fetching users:", error);
        this.hasMore = false;
      }
    } else {
      if (query.trim() === "") {
        filteredUsers = [...this.allUsers];
      } else {
        filteredUsers = this.allUsers.filter((user) =>
          user.name.toLowerCase().includes(query.toLowerCase())
        );
      }
      this.filteredUsers = filteredUsers;
      this.hasMore = false;
    }

    // Filter out already selected mentions
    this.filteredUsers = this.filteredUsers.filter(
      (user) => !this.selectedMentionIds.has(user.id)
    );

    this.isLoading = false;
    this.showDropdown();
  }

  private async loadMoreUsers() {
    if (!this.config.endpoint || this.isLoading || !this.hasMore) return;

    this.currentPage++;
    await this.searchUsers(this.searchQuery);
  }

  private showDropdown() {
    if (this.filteredUsers.length === 0 || !this.currentBlock) {
      this.closeDropdown();
      return;
    }

    if (!this.popoverContainer) {
      this.popoverContainer = document.createElement("div");
      document.body.appendChild(this.popoverContainer);
      this.reactRoot = createRoot(this.popoverContainer);
    }

    this.isOpen = true;
    this.renderPopover();
  }

  private renderPopover() {
    if (!this.reactRoot) return;

    this.reactRoot.render(
      <MentionDropdown
        users={this.filteredUsers}
        hasMore={this.hasMore}
        isLoading={this.isLoading}
        onSelect={(user) => this.insertMention(user)}
        onLoadMore={() => this.loadMoreUsers()}
        open={this.isOpen}
        position={this.dropdownPosition}
      />
    );
  }

  private insertMention(user: { id: string; name: string }) {
    if (!this.currentBlock) return;

    const selection = window.getSelection();
    if (!selection || selection.rangeCount === 0) return;

    const text = this.currentBlock.innerText || "";
    const cursorPos = this.getCursorPosition(this.currentBlock);

    const mentionSpan = document.createElement("span");
    mentionSpan.classList.add("mention");
    mentionSpan.setAttribute("data-mention-id", user.id);
    mentionSpan.setAttribute("data-mention-name", user.name);
    mentionSpan.setAttribute("contenteditable", "false");
    mentionSpan.textContent = `@${user.name}`;

    const range = document.createRange();
    const textNodes = this.getTextNodes(this.currentBlock);

    let currentLength = 0;
    let startNode: Node | null = null;
    let startOffset = 0;
    let endNode: Node | null = null;
    let endOffset = 0;

    for (const node of textNodes) {
      const nodeLength = node.textContent?.length || 0;

      if (!startNode && currentLength + nodeLength > this.mentionStart) {
        startNode = node;
        startOffset = this.mentionStart - currentLength;
      }

      if (!endNode && currentLength + nodeLength >= cursorPos) {
        endNode = node;
        endOffset = cursorPos - currentLength;
        break;
      }

      currentLength += nodeLength;
    }

    if (startNode && endNode) {
      range.setStart(startNode, startOffset);
      range.setEnd(endNode, endOffset);
      range.deleteContents();

      range.insertNode(mentionSpan);
      const space = document.createTextNode("\u00A0");
      mentionSpan.parentNode?.insertBefore(space, mentionSpan.nextSibling);

      range.setStartAfter(space);
      range.collapse(true);
      selection.removeAllRanges();
      selection.addRange(range);
    }

    // Add the user to selected mentions
    this.selectedMentionIds.add(user.id);

    this.closeDropdown();
    this.currentBlock.focus();
  }

  private getTextNodes(element: HTMLElement): Text[] {
    const textNodes: Text[] = [];
    const walker = document.createTreeWalker(
      element,
      NodeFilter.SHOW_TEXT,
      null
    );

    let node;
    while ((node = walker.nextNode())) {
      textNodes.push(node as Text);
    }

    return textNodes;
  }

  public closeDropdown() {
    this.isOpen = false;
    if (this.reactRoot) {
      this.reactRoot.unmount();
      this.reactRoot = null;
    }
    if (this.popoverContainer) {
      this.popoverContainer.remove();
      this.popoverContainer = null;
    }
    this.mentionStart = -1;
    this.searchQuery = "";
    this.filteredUsers = [];
    this.currentPage = 1;
    this.hasMore = false;
  }

  private getCursorPosition(element: HTMLElement): number {
    const selection = window.getSelection();
    if (!selection || selection.rangeCount === 0) return 0;

    const range = selection.getRangeAt(0);
    const preCaretRange = range.cloneRange();
    preCaretRange.selectNodeContents(element);
    preCaretRange.setEnd(range.endContainer, range.endOffset);

    return preCaretRange.toString().length;
  }
}
export const getMentionToolStyles = (primaryColor: string = "#2563eb") => {
  // Generate lighter shades of primary color
  const lightColor = `${primaryColor}20`; // 12% opacity
  const mediumColor = `${primaryColor}40`; // 25% opacity

  return `
.mention-dropdown {
  position: fixed;
  background: white;
  border: 1px solid #e5e7eb;
  border-radius: 8px;
  box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05);
  max-height: 280px;
  min-width: 240px;
  max-width: 320px;
  overflow-y: auto;
  z-index: 99999;
  padding: 4px;
}

.mention-dropdown::-webkit-scrollbar {
  width: 6px;
}

.mention-dropdown::-webkit-scrollbar-track {
  background: transparent;
}

.mention-dropdown::-webkit-scrollbar-thumb {
  background: #d1d5db;
  border-radius: 3px;
}

.mention-item {
  padding: 8px 10px;
  cursor: pointer;
  display: flex;
  align-items: center;
  gap: 10px;
  border-radius: 6px;
  transition: all 0.15s ease;
}

.mention-item:hover,
.mention-item.selected {
  background-color: ${lightColor};
}

.mention-avatar {
  width: 32px;
  height: 32px;
  border-radius: 50%;
  object-fit: cover;
  flex-shrink: 0;
}

.mention-avatar-placeholder {
  width: 32px;
  height: 32px;
  border-radius: 50%;
  background: ${primaryColor};
  color: white;
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: 600;
  font-size: 13px;
  flex-shrink: 0;
}

.mention {
  color: ${primaryColor};
  background-color: ${lightColor};
  padding: 2px 6px;
  border-radius: 4px;
  font-weight: 500;
  cursor: default;
  display: inline-block;
  user-select: none;
  transition: all 0.15s ease;
  cursor: pointer
}

.mention:hover {
  background-color: ${mediumColor};
}

.mention-loader {
  padding: 8px;
  text-align: center;
  font-size: 12px;
  color: #6b7280;
  font-style: italic;
}
`;
};
```

use as follows

```
import MentionTool, {
  getMentionToolStyles,
} from "../editorjs-tools/mention-tool";

 tools: {
 mention: {
            class: MentionTool,
            config: {
             //PASS USERS OR ENDPOINT URL. TOOL IS PAGINATED
              users: [{id: "", name: "", avatar: ""}]
             //FOR ENDPOINT, return in format , {users: [{id: "", name: "", avatar: ""}], hasMore: true/false(boolean)}
              endpoint: `${SERVER_URL}/api/usernames`,
              queryParam: "q",
              pageSize: 20,
              debounce: 300,
            },
          },
}```

**Comment by gs03-dev** [comment]
funny the component doesn't even work well in react, putting it here for people that might need a react impl
